package kraken

// Asset defines an asset within Kraken.
type Asset string

// AssetPair defines an asset pair within Kraken.
type AssetPair string

// AssetClass defines an asset class within Kraken.
type AssetClass string

const (
	Currency AssetClass = "currency"
)

// AssetInfo defines the information about an asset.
type AssetInfo struct {
	Altname         string     `json:"altname"`
	AssetClass      AssetClass `json:"aclass"`
	Decimals        int        `json:"decimals"`
	DisplayDecimals int        `json:"display_decimals"`
	Status          string     `json:"status"`
}

// Assets defines a map of assets.
type Assets map[Asset]AssetInfo

// Info returns the information about an asset.
func (a Assets) Info(asset Asset) AssetInfo {
	return a[asset]
}

const (
	GST      Asset = "GST"
	PHA      Asset = "PHA"
	SBR      Asset = "SBR"
	TRU      Asset = "TRU"
	AIR      Asset = "AIR"
	ALICE    Asset = "ALICE"
	BNC      Asset = "BNC"
	CTSI     Asset = "CTSI"
	USDC     Asset = "USDC"
	FLOWS    Asset = "FLOW.S"
	GHST     Asset = "GHST"
	XTZ      Asset = "XTZ"
	BAL      Asset = "BAL"
	DOT      Asset = "DOT"
	FORTH    Asset = "FORTH"
	YGG      Asset = "YGG"
	STORJ    Asset = "STORJ"
	USDCM    Asset = "USDC.M"
	XLTC     Asset = "XLTC"
	AUDHOLD  Asset = "AUD.HOLD"
	INTR     Asset = "INTR"
	OGN      Asset = "OGN"
	SEI      Asset = "SEI"
	EUL      Asset = "EUL"
	GARI     Asset = "GARI"
	MOVR     Asset = "MOVR"
	TRIBE    Asset = "TRIBE"
	FIL      Asset = "FIL"
	SOL03S   Asset = "SOL03.S"
	TVK      Asset = "TVK"
	UNI      Asset = "UNI"
	ADX      Asset = "ADX"
	DOT28S   Asset = "DOT28.S"
	SCRT     Asset = "SCRT"
	AED      Asset = "AED"
	SC       Asset = "SC"
	XCN      Asset = "XCN"
	ASTR     Asset = "ASTR"
	EGLD     Asset = "EGLD"
	KILT     Asset = "KILT"
	SXP      Asset = "SXP"
	AAVE     Asset = "AAVE"
	UNFI     Asset = "UNFI"
	SUI      Asset = "SUI"
	ADA      Asset = "ADA"
	EOS      Asset = "EOS"
	GBPHOLD  Asset = "GBP.HOLD"
	ICP      Asset = "ICP"
	SCRTS    Asset = "SCRT.S"
	XTZS     Asset = "XTZ.S"
	ZCAD     Asset = "ZCAD"
	CHF      Asset = "CHF"
	DOTP     Asset = "DOT.P"
	GMX      Asset = "GMX"
	OXT      Asset = "OXT"
	GMT      Asset = "GMT"
	INJ      Asset = "INJ"
	XREP     Asset = "XREP"
	ANKR     Asset = "ANKR"
	AXS      Asset = "AXS"
	BLZ      Asset = "BLZ"
	DASH     Asset = "DASH"
	GRTS     Asset = "GRT.S"
	PARA     Asset = "PARA"
	WOO      Asset = "WOO"
	ENS      Asset = "ENS"
	GLMR     Asset = "GLMR"
	NYM      Asset = "NYM"
	XXBT     Asset = "XXBT"
	APE      Asset = "APE"
	FXS      Asset = "FXS"
	USDHOLD  Asset = "USD.HOLD"
	TRX      Asset = "TRX"
	ONEINCH  Asset = "1INCH"
	BOND     Asset = "BOND"
	COMP     Asset = "COMP"
	POND     Asset = "POND"
	NEAR     Asset = "NEAR"
	PSTAKE   Asset = "PSTAKE"
	STEP     Asset = "STEP"
	XBTM     Asset = "XBT.M"
	API3     Asset = "API3"
	KSMS     Asset = "KSM.S"
	LSK      Asset = "LSK"
	MASK     Asset = "MASK"
	SUSHI    Asset = "SUSHI"
	ZGBP     Asset = "ZGBP"
	BTT      Asset = "BTT"
	DENT     Asset = "DENT"
	FET      Asset = "FET"
	MC       Asset = "MC"
	LUNA2    Asset = "LUNA2"
	RPL      Asset = "RPL"
	SRM      Asset = "SRM"
	ENJ      Asset = "ENJ"
	GALA     Asset = "GALA"
	KAR      Asset = "KAR"
	KAVA21S  Asset = "KAVA21.S"
	DOTS     Asset = "DOT.S"
	SUPER    Asset = "SUPER"
	ZRX      Asset = "ZRX"
	USDT     Asset = "USDT"
	CHR      Asset = "CHR"
	EURT     Asset = "EURT"
	NODL     Asset = "NODL"
	TBTC     Asset = "TBTC"
	XXMR     Asset = "XXMR"
	BCH      Asset = "BCH"
	KFEE     Asset = "KFEE"
	SYN      Asset = "SYN"
	TEER     Asset = "TEER"
	BAND     Asset = "BAND"
	ICX      Asset = "ICX"
	MINAS    Asset = "MINA.S"
	HDX      Asset = "HDX"
	RNDR     Asset = "RNDR"
	USDM     Asset = "USD.M"
	SDN      Asset = "SDN"
	ETH2S    Asset = "ETH2.S"
	FLOW     Asset = "FLOW"
	LDO      Asset = "LDO"
	LUNAS    Asset = "LUNA.S"
	IDEX     Asset = "IDEX"
	IMX      Asset = "IMX"
	SHIB     Asset = "SHIB"
	CHFHOLD  Asset = "CHF.HOLD"
	PEPE     Asset = "PEPE"
	XXRP     Asset = "XXRP"
	XZEC     Asset = "XZEC"
	BADGER   Asset = "BADGER"
	CRV      Asset = "CRV"
	ORCA     Asset = "ORCA"
	ROOK     Asset = "ROOK"
	BIT      Asset = "BIT"
	MANA     Asset = "MANA"
	YFI      Asset = "YFI"
	TUSD     Asset = "TUSD"
	FLOW14S  Asset = "FLOW14.S"
	GTC      Asset = "GTC"
	MATIC04S Asset = "MATIC04.S"
	RBC      Asset = "RBC"
	ALCX     Asset = "ALCX"
	STX      Asset = "STX"
	FIDA     Asset = "FIDA"
	T        Asset = "T"
	TOKE     Asset = "TOKE"
	KNC      Asset = "KNC"
	MIR      Asset = "MIR"
	ALGO     Asset = "ALGO"
	BAT      Asset = "BAT"
	CELR     Asset = "CELR"
	CQT      Asset = "CQT"
	FIS      Asset = "FIS"
	SOL      Asset = "SOL"
	TLM      Asset = "TLM"
	GAL      Asset = "GAL"
	KSM07S   Asset = "KSM07.S"
	LCX      Asset = "LCX"
	PAXG     Asset = "PAXG"
	AEDHOLD  Asset = "AED.HOLD"
	MNGO     Asset = "MNGO"
	ZAUD     Asset = "ZAUD"
	ZUSD     Asset = "ZUSD"
	RUNE     Asset = "RUNE"
	XETC     Asset = "XETC"
	ARPA     Asset = "ARPA"
	LPT      Asset = "LPT"
	PERP     Asset = "PERP"
	QNT      Asset = "QNT"
	ZEUR     Asset = "ZEUR"
	ACH      Asset = "ACH"
	ETH2     Asset = "ETH2"
	NANO     Asset = "NANO"
	UMA      Asset = "UMA"
	STG      Asset = "STG"
	LINK     Asset = "LINK"
	LMWR     Asset = "LMWR"
	REN      Asset = "REN"
	REPV2    Asset = "REPV2"
	KEEP     Asset = "KEEP"
	KIN      Asset = "KIN"
	MOON     Asset = "MOON"
	MV       Asset = "MV"
	AGLD     Asset = "AGLD"
	AKT      Asset = "AKT"
	ALGOS    Asset = "ALGO.S"
	ATOM     Asset = "ATOM"
	REQ      Asset = "REQ"
	USDTM    Asset = "USDT.M"
	CFG      Asset = "CFG"
	JASMY    Asset = "JASMY"
	KSM      Asset = "KSM"
	MINA     Asset = "MINA"
	KINT     Asset = "KINT"
	SAMO     Asset = "SAMO"
	SNX      Asset = "SNX"
	XXLM     Asset = "XXLM"
	ALPHA    Asset = "ALPHA"
	EWT      Asset = "EWT"
	FLOWH    Asset = "FLOWH"
	GRT28S   Asset = "GRT28.S"
	XRT      Asset = "XRT"
	ANT      Asset = "ANT"
	BNT      Asset = "BNT"
	KSMP     Asset = "KSM.P"
	SAND     Asset = "SAND"
	WAVES    Asset = "WAVES"
	ARB      Asset = "ARB"
	BLUR     Asset = "BLUR"
	BOBA     Asset = "BOBA"
	PLA      Asset = "PLA"
	ETHW     Asset = "ETHW"
	SGB      Asset = "SGB"
	WBTC     Asset = "WBTC"
	XMLN     Asset = "XMLN"
	ATOMS    Asset = "ATOM.S"
	CADHOLD  Asset = "CAD.HOLD"
	FLOWHS   Asset = "FLOWH.S"
	FLRS     Asset = "FLR.S"
	C98      Asset = "C98"
	GRT      Asset = "GRT"
	HFT      Asset = "HFT"
	OCEAN    Asset = "OCEAN"
	UST      Asset = "UST"
	OMG      Asset = "OMG"
	POLIS    Asset = "POLIS"
	POLS     Asset = "POLS"
	KEY      Asset = "KEY"
	KP3R     Asset = "KP3R"
	MATIC    Asset = "MATIC"
	XXDG     Asset = "XXDG"
	AVT      Asset = "AVT"
	CVC      Asset = "CVC"
	CVX      Asset = "CVX"
	FARM     Asset = "FARM"
	RLC      Asset = "RLC"
	ADAS     Asset = "ADA.S"
	EURM     Asset = "EUR.M"
	FLR      Asset = "FLR"
	KAVAS    Asset = "KAVA.S"
	SCRT21S  Asset = "SCRT21.S"
	TRXS     Asset = "TRX.S"
	WETH     Asset = "WETH"
	ATOM21S  Asset = "ATOM21.S"
	MXC      Asset = "MXC"
	OXY      Asset = "OXY"
	POWR     Asset = "POWR"
	JUNO     Asset = "JUNO"
	MKR      Asset = "MKR"
	BICO     Asset = "BICO"
	BRICK    Asset = "BRICK"
	COTI     Asset = "COTI"
	CSM      Asset = "CSM"
	APT      Asset = "APT"
	ATLAS    Asset = "ATLAS"
	WAXL     Asset = "WAXL"
	BSX      Asset = "BSX"
	FTM      Asset = "FTM"
	MULTI    Asset = "MULTI"
	SOLS     Asset = "SOL.S"
	QTUM     Asset = "QTUM"
	RARE     Asset = "RARE"
	ACA      Asset = "ACA"
	AVAX     Asset = "AVAX"
	EURHOLD  Asset = "EUR.HOLD"
	GNO      Asset = "GNO"
	CHZ      Asset = "CHZ"
	DYDX     Asset = "DYDX"
	PYUSD    Asset = "PYUSD"
	ZJPY     Asset = "ZJPY"
	MSOL     Asset = "MSOL"
	RAD      Asset = "RAD"
	RARI     Asset = "RARI"
	RAY      Asset = "RAY"
	AUDIO    Asset = "AUDIO"
	KAVA     Asset = "KAVA"
	LUNA     Asset = "LUNA"
	MATICS   Asset = "MATIC.S"
	XETH     Asset = "XETH"
	DAI      Asset = "DAI"
	LRC      Asset = "LRC"
	NMR      Asset = "NMR"
	SPELL    Asset = "SPELL"
)
